eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
#千万注意: 冒号后面要跟一个空格,否则值不生效
#用于开启 feign 的熔断机制
feign:
  hystrix:
    enabled: true

#配置 actuator 相关属性, 才能正常使用 HystrixDashboard
#http://localhost:8765/actuator/hystrix.stream
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"