#根据spring-boot-starter-parent资源文件的加载顺序，properties文件最后加载，因此优先级最高
server:
  port: 8082

#普通数据的配置
name: zhangsan

#对象的配置
person:
  name: zhangsan
  age: 18
  addr: beijing

#行内对象的配置
person2: {name: zhangsan,age: 18, addr: beijing}

#配置数据、集合(普通字符串)
city:
  - beijing
  - tianjing
  - chongqing
  - shanghai

#配置行内数据、集合(普通字符串)
city1: [beijing,tianjing,chongqing,shanghai]

#配置数据、集合(对象数据)
student:
  - name: tom
    age: 18
    addr: beijing
  - name: lucy
    age: 17
    addr: tianjing

#配置行内数据、集合(对象数据)
student1: [{name: tom, age: 18, addr: beijing},{name: lucy, age: 17, addr: tianjing}]

#Map配置
map:
  key1: value1
  key2: value2